apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rt7mrjt2k-python 
  janus-idp.io/tekton: rt7mrjt2k-python
  backstage.io/kubernetes-id: rt7mrjt2k-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rt7mrjt2k-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  